/**
 * ============================================================================
 * EMAIL TYPE DEFINITIONS
 * ============================================================================
 * 
 * This module contains all TypeScript type definitions and interfaces
 * used throughout the email management application.
 * 
 * These types ensure type safety and provide IntelliSense support
 * when working with email data structures across the application.
 * ============================================================================
 */

// Email types and interfaces

/**
 * Email category classification types.
 * 
 * These categories are used by the AI analysis system to classify emails
 * into different groups for better organization and filtering.
 * 
 * Categories are determined by the Gemini AI model during email analysis.
 */
export type EmailCategory = 
  | 'urgent' 
  | 'important' 
  | 'work' 
  | 'personal' 
  | 'promotions' 
  | 'spam' 
  | 'newsletter' 
  | 'social' 
  | 'uncategorized'; // Default fallback category when AI cannot determine a specific category

/**
 * Email priority levels for sorting and filtering.
 * 
 * Priority is determined by combining urgency and importance factors.
 * Used to help users focus on emails that require immediate attention.
 * 
 * Priority levels:
 * - critical: Requires immediate action (urgent + important)
 * - high: Important emails needing attention soon
 * - medium: Regular emails for normal workflow
 * - low: FYI emails, newsletters, low-priority notifications
 * - trash: Spam, promotions, or non-essential content
 */
export type EmailPriority = 'critical' | 'high' | 'medium' | 'low' | 'trash';

/**
 * Core Email interface representing a single email message.
 * 
 * This interface defines the structure of email objects used throughout
 * the application. It includes both standard email fields and AI-generated
 * metadata that enhances email management capabilities.
 * 
 * Standard fields are populated from the database, while AI-generated
 * fields are populated by the Gemini AI analysis service.
 */
export interface Email {
  // ========================================================================
  // STANDARD EMAIL FIELDS
  // ========================================================================
  // These fields are standard email properties stored in the database
  
  /** Unique identifier for the email (UUID) */
  id: string;
  /** Sender's email address */
  from: string;
  /** Recipient's email address */
  to: string;
  /** Email subject line */
  subject: string;
  /** Full email body content */
  body: string;
  /** Date and time when the email was received/sent */
  date: Date;
  /** Whether the email has been read by the user */
  read: boolean;
  /** Whether the email has been starred/favorited by the user */
  starred: boolean;
  /** Type of email: 'inbox' for received emails, 'sent' for sent emails */
  email_type?: 'inbox' | 'sent';
  
  // ========================================================================
  // AI-GENERATED FIELDS
  // ========================================================================
  // These fields are populated by the Gemini AI analysis service
  // They provide intelligent categorization and insights about the email
  
  /** 
   * AI-generated summary of the email content.
   * Typically 1-2 sentences providing a concise overview.
   * Generated by the Gemini AI model during email analysis.
   */
  summary?: string;
  /** 
   * AI-determined category classification.
   * Categorizes the email into one of the predefined EmailCategory types.
   * Helps with email organization and filtering.
   */
  category?: EmailCategory;
  /** 
   * AI-determined priority level.
   * Indicates the urgency and importance of the email.
   * Used for sorting and highlighting important emails.
   */
  priority?: EmailPriority;
  /** 
   * Sentiment analysis result.
   * Indicates the emotional tone of the email content.
   * Values: 'positive', 'neutral', or 'negative'
   */
  sentiment?: 'positive' | 'neutral' | 'negative';
  /** 
   * Whether the email requires a response or action from the user.
   * Determined by analyzing the email content for action items,
   * questions, or requests.
   */
  actionRequired?: boolean;
  /** 
   * AI confidence score for the analysis (0-1).
   * Higher values indicate higher confidence in the AI's analysis.
   * Values closer to 1.0 mean the AI is more certain about its categorization.
   */
  confidence?: number; // AI confidence score 0-1
}

/**
 * Complete email analysis result structure.
 * 
 * This interface represents the full analysis output from the Gemini AI model.
 * It contains all the structured data extracted from analyzing an email,
 * including categorization, sentiment, key points, and suggested actions.
 * 
 * This is the return type from the GeminiService.analyzeEmail() method.
 */
export interface EmailAnalysis {
  /** Concise 1-2 sentence summary of the email content */
  summary: string;
  /** Categorized classification of the email */
  category: EmailCategory;
  /** Priority level assigned to the email */
  priority: EmailPriority;
  /** Sentiment analysis result: positive, neutral, or negative */
  sentiment: 'positive' | 'neutral' | 'negative';
  /** Whether the email requires user action or response */
  actionRequired: boolean;
  /** Array of key points extracted from the email content */
  keyPoints: string[];
  /** Optional AI-generated suggested response text */
  suggestedResponse?: string;
  /** Confidence score (0-1) indicating AI's certainty in the analysis */
  confidence: number;
}

/**
 * Statistics interface for email categories.
 * 
 * Used for displaying category counts in the UI sidebar filters.
 * Provides both the category name and its count, along with
 * a color identifier for visual representation.
 * 
 * This is typically used to show how many emails are in each category
 * to help users understand their email distribution.
 */
export interface CategoryStats {
  /** The email category this statistic represents */
  category: EmailCategory;
  /** Number of emails in this category */
  count: number;
  /** Color identifier for UI display (CSS color value or Tailwind class) */
  color: string;
}

